name: brewblox-ui
services:
  eventbus:
    image: ghcr.io/brewblox/mosquitto:develop
    labels:
      - traefik.http.services.eventbus.loadbalancer.server.port=15675

  victoria:
    image: victoriametrics/victoria-metrics:v1.88.0
    command: >-
      --retentionPeriod=100y
      --influxMeasurementFieldSeparator=/
      --http.pathPrefix=/victoria
      --search.latencyOffset=10s
    labels:
      - traefik.http.services.victoria.loadbalancer.server.port=8428
    volumes:
      - type: bind
        source: ${BREWBLOX_CACHE_DIR}/victoria
        target: /victoria-metrics-data

  redis:
    image: redis:6.0
    command: --appendonly yes
    labels:
      - traefik.enable=false
    volumes:
      - type: bind
        source: ${BREWBLOX_CACHE_DIR}/redis
        target: /data

  history:
    image: ghcr.io/brewblox/brewblox-history:develop

  node-red:
    image: ghcr.io/brewblox/node-red:develop
    volumes:
      - type: bind
        source: ${BREWBLOX_CACHE_DIR}/node-red
        target: /data

  sparkey:
    image: ghcr.io/brewblox/brewblox-devcon-spark:develop
    command: --name=sparkey --simulation --device-id=123456789012345678901234
    restart: unless-stopped
    privileged: true
    volumes:
      - type: bind
        source: ${BREWBLOX_CACHE_DIR}/simulator__sparkey
        target: /app/simulator

  spock:
    image: ghcr.io/brewblox/brewblox-devcon-spark:develop
    command: --name=spock --simulation --device-id=432109876543210987654321
    restart: unless-stopped
    privileged: true
    volumes:
      - type: bind
        source: ${BREWBLOX_CACHE_DIR}/simulator__spock
        target: /app/simulator

  tilt:
    image: ghcr.io/brewblox/brewblox-tilt:develop
    labels:
      - traefik.enable=false
    volumes:
      - type: bind
        source: ${BREWBLOX_CACHE_DIR}/tilt
        target: /share
    restart: unless-stopped
    network_mode: host
    privileged: true
    command: --mqtt-port=9001 --simulate=Pink

  auth:
    image: ghcr.io/brewblox/brewblox-auth:develop
    environment:
      - BREWBLOX_AUTH_ENABLED=False
      - BREWBLOX_AUTH_IGNORE=/|/ui/.*|/static/.*
    volumes:
      - type: bind
        source: ./dev/auth
        target: /app/data

  traefik:
    image: traefik:2.10
    ports:
      - '9000:9000'
      - '9001:9001'
      - '127.0.0.1:9601:9601'
    labels:
      - traefik.http.routers.api.rule=PathPrefix(`/api`) || PathPrefix(`/dashboard`)
      - traefik.http.routers.api.service=api@internal
      - traefik.http.middlewares.prefix-strip.stripprefixregex.regex=/[^/]+
      - traefik.http.middlewares.auth.forwardauth.address=http://auth:5000/auth/verify
      - traefik.http.middlewares.cors.headers.AccessControlAllowMethods=CONNECT,HEAD,GET,DELETE,OPTIONS,PATCH,POST,PUT,TRACE
      - traefik.http.middlewares.cors.headers.accessControlAllowOriginListRegex=.*
      - traefik.http.middlewares.cors.headers.AccessControlAllowCredentials=true
      - traefik.http.middlewares.cors.headers.AccessControlAllowHeaders=Origin,X-Requested-With,Content-Type,Accept
    volumes:
      - type: bind
        source: ./dev/traefik
        target: /config
        read_only: true
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    command: >-
      --api.dashboard=true
      --providers.docker=true
      --providers.docker.constraints="Label(`com.docker.compose.project`, `${COMPOSE_PROJECT_NAME}`)"
      --providers.docker.defaultrule="PathPrefix(`/{{ index .Labels \"com.docker.compose.service\" }}`)"
      --providers.file.directory=/config
      --entrypoints.websecure.address=:9001
      --entrypoints.websecure.http.tls=true
      --entrypoints.websecure.http.middlewares=cors,auth
      --entrypoints.web.address=:9000
      --entrypoints.web.http.redirections.entrypoint.to=websecure
      --entrypoints.admin.address=:9601
      --entrypoints.admin.http.middlewares=cors
