version: "3.7"

services:
  eventbus:
    image: brewblox/mosquitto:develop
    labels:
      - traefik.http.services.eventbus.loadbalancer.server.port=15675

  victoria:
    image: victoriametrics/victoria-metrics:v1.69.0
    labels:
      - traefik.http.services.victoria.loadbalancer.server.port=8428
    volumes:
      - type: bind
        source: ./dev/victoria
        target: /victoria-metrics-data
    command: >-
      --retentionPeriod=100y
      --influxMeasurementFieldSeparator=/
      --http.pathPrefix=/victoria

  redis:
    image: redis:6.2
    labels:
      - traefik.enable=false
    volumes:
      - type: bind
        source: ./dev/redis
        target: /data
    command: --appendonly yes

  history:
    image: brewblox/brewblox-history:develop

  node-red:
    image: brewblox/node-red:develop
    volumes:
      - type: bind
        source: ./dev/node-red
        target: /data

  sparkey:
    image: brewblox/brewblox-devcon-spark:develop
    restart: unless-stopped
    privileged: true
    volumes:
      - type: bind
        source: ./dev/simulator__sparkey
        target: /app/simulator
    command: --name=sparkey --simulation --device-id=123456789012345678901234

  spock:
    image: brewblox/brewblox-devcon-spark:develop
    restart: unless-stopped
    privileged: true
    volumes:
      - type: bind
        source: ./dev/simulator__spock
        target: /app/simulator
    command: --name=spock --simulation --device-id=432109876543210987654321

  tilt:
    image: brewblox/brewblox-tilt:develop
    labels:
      - traefik.enable=false
    volumes:
      - type: bind
        source: ./dev/tilt_share
        target: /share
    restart: unless-stopped
    network_mode: host
    privileged: true
    command: --mqtt-port=9001 --simulate=Pink

  traefik:
    image: traefik:2.2
    ports:
      - "9000:9000"
      - "9001:9001"
    labels:
      - traefik.http.routers.api.rule=PathPrefix(`/api`) || PathPrefix(`/dashboard`)
      - traefik.http.routers.api.service=api@internal
      - traefik.http.middlewares.prefix-strip.stripprefixregex.regex=/[^/]+
    volumes:
      - type: bind
        source: ./dev/traefik
        target: /config
        read_only: true
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    command: >-
      --api.dashboard=true
      --providers.docker=true
      --providers.docker.constraints="Label(`com.docker.compose.project`, `brewblox-ui`)"
      --providers.docker.defaultrule="PathPrefix(`/{{ index .Labels \"com.docker.compose.service\" }}`)"
      --providers.file.directory=/config
      --entrypoints.web.address=:9000
      --entrypoints.websecure.address=:9001
      --entrypoints.websecure.http.tls=true
    # --entrypoints.web.http.redirections.entrypoint.to=websecure
