version: "3.7"

services:
  eventbus:
    image: brewblox/mosquitto:develop
    labels:
      - traefik.http.services.eventbus.loadbalancer.server.port=15675

  influx:
    image: influxdb:1.8
    labels:
      - traefik.enable=false
    volumes:
      - ./dev/influxdb/:/var/lib/influxdb/

  redis:
    image: redis:6.0
    labels:
      - traefik.enable=false
    volumes:
      - ./dev/redis:/data
    command: --appendonly yes

  history:
    image: brewblox/brewblox-history:develop

  node-red:
    image: brewblox/node-red:develop
    volumes:
      - ./dev/node-red:/data

  sparkey:
    image: brewblox/brewblox-devcon-spark:develop
    restart: unless-stopped
    privileged: true
    volumes:
      - ./dev/simulator__sparkey:/app/simulator
    command: --name=sparkey --simulation --device-id=123456789012345678901234

  spock:
    image: brewblox/brewblox-devcon-spark:develop
    restart: unless-stopped
    privileged: true
    volumes:
      - ./dev/simulator__spock:/app/simulator
    command: --name=spock --simulation --device-id=432109876543210987654321

  tilt:
    image: brewblox/brewblox-tilt:develop
    labels:
      - traefik.enable=false
    restart: unless-stopped
    command: --simulate=Pink --mqtt-host=eventbus --mqtt-protocol=mqtt

  traefik:
    image: traefik:2.2
    ports:
      - "9000:9000"
      - "9001:9001"
    labels:
      - traefik.http.routers.api.rule=PathPrefix(`/api`) || PathPrefix(`/dashboard`)
      - traefik.http.routers.api.service=api@internal
      - traefik.http.middlewares.prefix-strip.stripprefixregex.regex=/[^/]+
    volumes:
      - ./dev/traefik:/config
      - /var/run/docker.sock:/var/run/docker.sock
    command: >-
      --api.dashboard=true
      --providers.docker=true
      --providers.docker.constraints="Label(`com.docker.compose.project`, `brewblox-ui`)"
      --providers.docker.defaultrule="PathPrefix(`/{{ index .Labels \"com.docker.compose.service\" }}`)"
      --providers.file.directory=/config
      --entrypoints.web.address=:9000
      --entrypoints.websecure.address=:9001
      --entrypoints.websecure.http.tls=true
    # --entrypoints.web.http.redirections.entrypoint.to=websecure
