# Configuration in this file is merged with docker-compose.yml
# You can use it to make local changes to the configuration
# Some common configurations are added in comments below
services:
  ui:
    build: .
    volumes:
      - type: bind
        source: ./dist
        target: /var/www/ui
      - type: bind
        source: ./dev/traefik/minica.pem
        target: /var/www/static/minica.pem
        read_only: true
      - type: bind
        source: ./dev/traefik/minica.der
        target: /var/www/static/minica.der
        read_only: true
    labels:
      - traefik.http.routers.ui.rule=PathPrefix(`/ui`) || PathPrefix(`/static`) || Path(`/`)

  # history:
  #   volumes:
  #     - type: bind
  #       source: ../brewblox-history/brewblox_history
  #       target: /app/brewblox_history

  # sparkey:
  #   volumes:
  #     - type: bind
  #       source: ../brewblox-devcon-spark/firmware
  #       target: /app/firmware
  #     - type: bind
  #       source: ../brewblox-devcon-spark/brewblox_devcon_spark
  #       target: /app/brewblox_devcon_spark
  #   ports:
  #     - '5678:5678'
  #   environment:
  #     - ENABLE_DEBUGGER=1
  #   labels:
  #     - traefik.http.services.sparkey.loadbalancer.server.port=5000

  # spock:
  #   volumes:
  #     - type: bind
  #       source: ../brewblox-devcon-spark/firmware
  #       target: /app/firmware
  #     - type: bind
  #       source: ../brewblox-devcon-spark/brewblox_devcon_spark
  #       target: /app/brewblox_devcon_spark

  # tilt:
  #   volumes:
  #     - type: bind
  #       source: ../brewblox-tilt/brewblox_tilt
  #       target: /app/brewblox_tilt
  #       read_only: true
  #     - type: bind
  #       source: ${BREWBLOX_CACHE_DIR}/tilt
  #       target: /share

  # hass:
  #   image: ghcr.io/brewblox/brewblox-hass:develop
  #   restart: unless-stopped
  #   volumes:
  #     - type: bind
  #       source: ../brewblox-hass/brewblox_hass
  #       target: /app/brewblox_hass

  # auth:
  #   volumes:
  #     - type: bind
  #       source: ../brewblox-auth/brewblox_auth
  #       target: /app/brewblox_auth
  #     - type: bind
  #       source: ../brewblox-auth/entrypoint.sh
  #       target: /app/entrypoint.sh

  # You need to change "enp8s0" to the name of your physical network interface
  # reflector:
  #   image: yuxzhu/mdns-reflector:latest
  #   restart: on-failure:3
  #   network_mode: host
  #   labels:
  #     - traefik.enable=false
  #   command: mdns-reflector -fn4 enp8s0 br-${COMPOSE_PROJECT_NAME}
