name: brewblox-ui

networks:
  default:
    driver_opts:
      com.docker.network.bridge.name: br-${COMPOSE_PROJECT_NAME}

services:
  eventbus:
    image: ghcr.io/brewblox/mosquitto:develop
    labels:
      # MQTT
      - traefik.tcp.routers.mqtt.entrypoints=mqtt
      - traefik.tcp.routers.mqtt.rule=HostSNI(`*`)
      - traefik.tcp.routers.mqtt.tls=false
      - traefik.tcp.routers.mqtt.service=mqtt
      - traefik.tcp.services.mqtt.loadbalancer.server.port=1883
      # MQTTS with TLS termination by traefik
      - traefik.tcp.routers.mqtts.entrypoints=mqtts
      - traefik.tcp.routers.mqtts.rule=HostSNI(`*`)
      - traefik.tcp.routers.mqtts.tls=true
      - traefik.tcp.routers.mqtts.service=mqtts
      - traefik.tcp.services.mqtts.loadbalancer.server.port=1884
      # MQTT over websockets
      - traefik.http.services.eventbus.loadbalancer.server.port=15675

  victoria:
    image: victoriametrics/victoria-metrics:v1.98.0
    command: --envflag.enable=true --envflag.prefix=VM_
    labels:
      - traefik.http.services.victoria.loadbalancer.server.port=8428
    environment:
      - VM_retentionPeriod=7d
      - VM_influxMeasurementFieldSeparator=/
      - VM_http_pathPrefix=/victoria
      - VM_search_latencyOffset=1s
    volumes:
      - type: bind
        source: ${BREWBLOX_CACHE_DIR}/victoria
        target: /victoria-metrics-data

  redis:
    image: redis:6.0
    command: --appendonly yes
    labels:
      - traefik.enable=false
    volumes:
      - type: bind
        source: ${BREWBLOX_CACHE_DIR}/redis
        target: /data

  history:
    image: ghcr.io/brewblox/brewblox-history:develop
    environment:
      - BREWBLOX_HISTORY_RANGES_INTERVAL=1s
      - BREWBLOX_HISTORY_MINIMUM_STEP=1s

  node-red:
    image: nodered/node-red:latest-minimal
    volumes:
      - type: bind
        source: ${BREWBLOX_CACHE_DIR}/node-red
        target: /data

  sparkey:
    image: ghcr.io/brewblox/brewblox-devcon-spark:develop
    restart: unless-stopped
    privileged: true
    environment:
      - BREWBLOX_SPARK_SIMULATION=true
      - BREWBLOX_SPARK_DEVICE_ID=123456789012345678901234
      - BREWBLOX_SPARK_BROADCAST_INTERVAL=1s
    volumes:
      - type: bind
        source: ${BREWBLOX_CACHE_DIR}/simulator__sparkey
        target: /app/simulator

  spock:
    image: ghcr.io/brewblox/brewblox-devcon-spark:develop
    restart: unless-stopped
    privileged: true
    environment:
      - BREWBLOX_SPARK_SIMULATION=true
      - BREWBLOX_SPARK_DEVICE_ID=432109876543210987654321
      - BREWBLOX_SPARK_BROADCAST_INTERVAL=1s
    volumes:
      - type: bind
        source: ${BREWBLOX_CACHE_DIR}/simulator__spock
        target: /app/simulator

  usb-proxy:
    image: ghcr.io/brewblox/brewblox-usb-proxy:develop
    restart: unless-stopped
    privileged: true
    labels:
      - traefik.http.services.usb-proxy.loadbalancer.server.port=5000

  tilt:
    image: ghcr.io/brewblox/brewblox-tilt:develop
    restart: unless-stopped
    privileged: true
    labels:
      - traefik.enable=false
    environment:
      - BREWBLOX_TILT_SIMULATE=["Pink"]
    volumes:
      - type: bind
        source: ${BREWBLOX_CACHE_DIR}/tilt
        target: /share

  auth:
    image: ghcr.io/brewblox/brewblox-auth:develop
    environment:
      - BREWBLOX_AUTH_ENABLED=False
      - BREWBLOX_AUTH_IGNORE=/|/(ui|static)/.*
    volumes:
      - type: bind
        source: ./dev/auth
        target: /app/data

  traefik:
    image: traefik:3.6
    command: --configFile=/config/traefik.yml
    ports:
      - '9000:9000'
      - '9001:9001'
      # MQTT and MQTTS use non-default host ports,
      # to avoid conflicts with a Brewblox install on the same host
      - '9883:1883'
      - '9884:8883'
      - '127.0.0.1:9601:9601'
    volumes:
      - type: bind
        source: ./dev/traefik
        target: /config
        read_only: true
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
