version: '3.7'

# Configuration in this file is merged with docker-compose.yml
# You can use it to make local changes to the configuration
# Some common configurations are added in comments below
services:
  ui:
    image: brewblox/brewblox-ui:develop
    volumes:
      - type: bind
        source: ./dist
        target: /usr/share/nginx/html/ui
      - type: bind
        source: ./docker/conf/default.conf
        target: /etc/nginx/conf.d/default.conf
    labels:
      - traefik.http.routers.ui.rule=PathPrefix(`/ui`) || Path(`/`)

  # node-red:
  #   volumes:
  #     - type: bind
  #       source: ./dev/node-red
  #       target: /data
  #     - type: bind
  #       source: ../node-red-contrib-brewblox
  #       target: /node-red-contrib-brewblox

  # automation:
  #   image: brewblox/brewblox-automation:develop
  #   init: true
  #   volumes:
  #     - type: bind
  #       source: ../brewblox-automation
  #       target: /app
  #   entrypoint: 'npm run dev'

  # automation-ui:
  #   image: brewblox/brewblox-automation-ui:develop
  # sparksimulator:
  #   image: brewblox/firmware-simulator:feature-multiplatform
  #   init: true
  #   ports:
  #     - "7376:7376"

  # history:
  #   image: brewblox/brewblox-history:develop
  #   volumes:
  #     - type: bind
  #       source: ../brewblox-history
  #       target: /app

  # sparkey:
  #   volumes:
  #     - type: bind
  #       source: ../brewblox-devcon-spark/firmware
  #       target: /app/firmware
  #     - type: bind
  #       source: ../brewblox-devcon-spark/brewblox_devcon_spark
  #       target: /app/brewblox_devcon_spark
  #   ports:
  #     - "5678:5678"
  #   environment:
  #     - ENABLE_DEBUGGER=1
  #   labels:
  #     - traefik.http.services.sparkey.loadbalancer.server.port=5000

  # spock:
  #   volumes:
  #     - type: bind
  #       source: ../brewblox-devcon-spark/firmware
  #       target: /app/firmware
  #     - type: bind
  #       source: ../brewblox-devcon-spark/brewblox_devcon_spark
  #       target: /app/brewblox_devcon_spark

  # tilt:
  #   volumes:
  #     - type: bind
  #       source: ../brewblox-tilt
  #       target: /app
  #       read_only: true
  #     - type: bind
  #       source: ./dev/tilt_share
  #       target: /share
