import {
  BORDER_KEY,
  COLD_WATER,
  COLOR_KEY,
  DRIVER_KEY,
  IO_ENABLED_KEY,
  IO_PRESSURE_KEY,
  PID_KEY,
  PWM_KEY,
  SETPOINT_KEY,
  VALVE_CLOSED_KEY,
} from '@/plugins/builder/const';
import { BuilderLayout } from '@/plugins/builder/types';
import { BlockAddress } from '@/plugins/spark/types';
import { typed } from '@/utils/misc';
import { nanoid } from 'nanoid';
import { withPrefix } from '../utils';
import { HermsConfig } from './types';

export function defineLayouts(config: HermsConfig): BuilderLayout[] {
  const { serviceId, names } = config;
  return [
    {
      id: nanoid(),
      title: withPrefix(config.prefix, 'Layout'),
      width: 26,
      height: 11,
      parts: [
        {
          id: nanoid(),
          rotate: 0,
          settings: {
            [COLOR_KEY]: '#c48600',
          },
          flipped: false,
          type: 'Kettle',
          x: 20,
          y: 1,
          width: 4,
          height: 6,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {
            [COLOR_KEY]: '#9c4b00',
          },
          flipped: false,
          type: 'Kettle',
          x: 12,
          y: 1,
          width: 4,
          height: 6,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {
            [COLOR_KEY]: '#b50000',
          },
          flipped: false,
          type: 'Kettle',
          x: 4,
          y: 1,
          width: 4,
          height: 6,
        },
        {
          id: nanoid(),
          rotate: 180,
          settings: {},
          flipped: false,
          type: 'Coil',
          x: 5,
          y: 4,
          width: 3,
          height: 2,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {
            [PWM_KEY]: typed<BlockAddress>({
              serviceId,
              id: names.bkPwm,
              type: null,
            }),
          },
          flipped: true,
          type: 'HeatingElement',
          x: 21,
          y: 6,
          width: 4,
          height: 1,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {
            [PWM_KEY]: typed<BlockAddress>({
              serviceId,
              id: names.hltPwm,
              type: null,
            }),
          },
          flipped: false,
          type: 'HeatingElement',
          x: 3,
          y: 6,
          width: 4,
          height: 1,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {},
          flipped: false,
          type: 'WhirlpoolInlet',
          x: 20,
          y: 2,
          width: 1,
          height: 4,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {},
          flipped: false,
          type: 'WhirlpoolInlet',
          x: 4,
          y: 2,
          width: 1,
          height: 4,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {},
          flipped: true,
          type: 'FilterBottom',
          x: 12,
          y: 6,
          width: 4,
          height: 1,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {
            [BORDER_KEY]: false,
            [SETPOINT_KEY]: typed<BlockAddress>({
              serviceId,
              id: names.mtSetpoint,
              type: null,
            }),
          },
          flipped: false,
          type: 'SetpointDisplay',
          x: 13,
          y: 3,
          width: 2,
          height: 1,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {
            [BORDER_KEY]: false,
            [SETPOINT_KEY]: typed<BlockAddress>({
              serviceId,
              id: names.bkSetpoint,
              type: null,
            }),
          },
          flipped: false,
          type: 'SetpointDisplay',
          x: 21,
          y: 3,
          width: 2,
          height: 1,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {
            [BORDER_KEY]: false,
            [SETPOINT_KEY]: typed<BlockAddress>({
              serviceId,
              id: names.hltSetpoint,
              type: null,
            }),
          },
          flipped: false,
          type: 'SetpointDisplay',
          x: 5,
          y: 3,
          width: 2,
          height: 1,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {},
          flipped: false,
          type: 'StraightTube',
          x: 19,
          y: 2,
          width: 1,
          height: 1,
        },
        {
          id: nanoid(),
          rotate: 90,
          settings: {},
          flipped: false,
          type: 'ElbowTube',
          x: 18,
          y: 2,
          width: 1,
          height: 1,
        },
        {
          id: nanoid(),
          rotate: 90,
          settings: {},
          flipped: false,
          type: 'StraightTube',
          x: 18,
          y: 3,
          width: 1,
          height: 1,
        },
        {
          id: nanoid(),
          rotate: 90,
          settings: {},
          flipped: false,
          type: 'StraightTube',
          x: 18,
          y: 4,
          width: 1,
          height: 1,
        },
        {
          id: nanoid(),
          rotate: 90,
          settings: {},
          flipped: false,
          type: 'StraightTube',
          x: 18,
          y: 5,
          width: 1,
          height: 1,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {},
          flipped: false,
          type: 'BridgeTube',
          x: 18,
          y: 6,
          width: 1,
          height: 1,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {},
          flipped: false,
          type: 'StraightTube',
          x: 11,
          y: 2,
          width: 1,
          height: 1,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {},
          flipped: false,
          type: 'StraightTube',
          x: 10,
          y: 2,
          width: 1,
          height: 1,
        },
        {
          id: nanoid(),
          rotate: 90,
          settings: {},
          flipped: false,
          type: 'ElbowTube',
          x: 9,
          y: 2,
          width: 1,
          height: 1,
        },
        {
          id: nanoid(),
          rotate: 90,
          settings: {},
          flipped: false,
          type: 'StraightTube',
          x: 11,
          y: 6,
          width: 1,
          height: 1,
        },
        {
          id: nanoid(),
          rotate: 90,
          settings: {},
          flipped: false,
          type: 'StraightTube',
          x: 10,
          y: 6,
          width: 1,
          height: 1,
        },
        {
          id: nanoid(),
          rotate: 90,
          settings: {},
          flipped: false,
          type: 'StraightTube',
          x: 9,
          y: 6,
          width: 1,
          height: 1,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {},
          flipped: false,
          type: 'DipTube',
          x: 12,
          y: 2,
          width: 1,
          height: 1,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {},
          flipped: false,
          type: 'DipTube',
          x: 20,
          y: 6,
          width: 1,
          height: 1,
        },
        {
          id: nanoid(),
          rotate: 180,
          settings: {},
          flipped: false,
          type: 'TeeTube',
          x: 17,
          y: 6,
          width: 1,
          height: 1,
        },
        {
          id: nanoid(),
          rotate: 180,
          settings: {
            [VALVE_CLOSED_KEY]: true,
          },
          flipped: false,
          type: 'Valve',
          x: 16,
          y: 6,
          width: 1,
          height: 1,
        },
        {
          id: nanoid(),
          rotate: 180,
          settings: {
            [VALVE_CLOSED_KEY]: true,
          },
          flipped: false,
          type: 'Valve',
          x: 19,
          y: 6,
          width: 1,
          height: 1,
        },
        {
          id: nanoid(),
          rotate: 90,
          settings: {},
          flipped: false,
          type: 'ElbowTube',
          x: 2,
          y: 2,
          width: 1,
          height: 1,
        },
        {
          id: nanoid(),
          rotate: 90,
          settings: {},
          flipped: false,
          type: 'StraightTube',
          x: 2,
          y: 3,
          width: 1,
          height: 1,
        },
        {
          id: nanoid(),
          rotate: 90,
          settings: {},
          flipped: false,
          type: 'StraightTube',
          x: 2,
          y: 4,
          width: 1,
          height: 1,
        },
        {
          id: nanoid(),
          rotate: 90,
          settings: {},
          flipped: false,
          type: 'StraightTube',
          x: 2,
          y: 5,
          width: 1,
          height: 1,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {},
          flipped: true,
          type: 'DipTube',
          x: 7,
          y: 6,
          width: 1,
          height: 1,
        },
        {
          id: nanoid(),
          rotate: 180,
          settings: {},
          flipped: false,
          type: 'ElbowTube',
          x: 8,
          y: 6,
          width: 1,
          height: 1,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {},
          flipped: false,
          type: 'TeeTube',
          x: 17,
          y: 9,
          width: 1,
          height: 1,
        },
        {
          id: nanoid(),
          rotate: 270,
          settings: {
            [VALVE_CLOSED_KEY]: true,
          },
          flipped: false,
          type: 'Valve',
          x: 18,
          y: 8,
          width: 1,
          height: 1,
        },
        {
          id: nanoid(),
          rotate: 90,
          settings: {},
          flipped: false,
          type: 'StraightTube',
          x: 18,
          y: 7,
          width: 1,
          height: 1,
        },
        {
          id: nanoid(),
          rotate: 90,
          settings: {},
          flipped: false,
          type: 'StraightTube',
          x: 17,
          y: 7,
          width: 1,
          height: 1,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {},
          flipped: false,
          type: 'StraightTube',
          x: 15,
          y: 9,
          width: 1,
          height: 1,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {},
          flipped: false,
          type: 'TeeTube',
          x: 9,
          y: 9,
          width: 1,
          height: 1,
        },
        {
          id: nanoid(),
          rotate: 270,
          settings: {
            [IO_ENABLED_KEY]: false,
          },
          flipped: false,
          type: 'Pump',
          x: 17,
          y: 8,
          width: 1,
          height: 1,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {},
          flipped: false,
          type: 'StraightTube',
          x: 3,
          y: 9,
          width: 1,
          height: 1,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {},
          flipped: false,
          type: 'StraightTube',
          x: 4,
          y: 9,
          width: 1,
          height: 1,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {},
          flipped: false,
          type: 'StraightTube',
          x: 5,
          y: 9,
          width: 1,
          height: 1,
        },
        {
          id: nanoid(),
          rotate: 90,
          settings: {},
          flipped: false,
          type: 'StraightTube',
          x: 2,
          y: 6,
          width: 1,
          height: 1,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {},
          flipped: false,
          type: 'StraightTube',
          x: 3,
          y: 2,
          width: 1,
          height: 1,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {},
          flipped: false,
          type: 'TeeTube',
          x: 13,
          y: 9,
          width: 1,
          height: 1,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {},
          flipped: false,
          type: 'TeeTube',
          x: 11,
          y: 9,
          width: 1,
          height: 1,
        },
        {
          id: nanoid(),
          rotate: 90,
          settings: {
            [VALVE_CLOSED_KEY]: true,
          },
          flipped: false,
          type: 'Valve',
          x: 13,
          y: 8,
          width: 1,
          height: 1,
        },
        {
          id: nanoid(),
          rotate: 90,
          settings: {
            [VALVE_CLOSED_KEY]: true,
          },
          flipped: false,
          type: 'Valve',
          x: 11,
          y: 8,
          width: 1,
          height: 1,
        },
        {
          id: nanoid(),
          rotate: 90,
          settings: {
            [VALVE_CLOSED_KEY]: true,
          },
          flipped: false,
          type: 'Valve',
          x: 9,
          y: 8,
          width: 1,
          height: 1,
        },
        {
          id: nanoid(),
          rotate: 90,
          settings: {},
          flipped: false,
          type: 'StraightTube',
          x: 9,
          y: 7,
          width: 1,
          height: 1,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {},
          flipped: false,
          type: 'StraightTube',
          x: 12,
          y: 7,
          width: 1,
          height: 1,
        },
        {
          id: nanoid(),
          rotate: 180,
          settings: {
            [VALVE_CLOSED_KEY]: true,
          },
          flipped: false,
          type: 'Valve',
          x: 10,
          y: 9,
          width: 1,
          height: 1,
        },
        {
          id: nanoid(),
          rotate: 180,
          settings: {
            [VALVE_CLOSED_KEY]: true,
          },
          flipped: false,
          type: 'Valve',
          x: 12,
          y: 9,
          width: 1,
          height: 1,
        },
        {
          id: nanoid(),
          rotate: 180,
          settings: {},
          flipped: false,
          type: 'ElbowTube',
          x: 13,
          y: 7,
          width: 1,
          height: 1,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {},
          flipped: false,
          type: 'BridgeTube',
          x: 11,
          y: 7,
          width: 1,
          height: 1,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {},
          flipped: false,
          type: 'ElbowTube',
          x: 10,
          y: 7,
          width: 1,
          height: 1,
        },
        {
          id: nanoid(),
          rotate: 90,
          settings: {},
          flipped: false,
          type: 'StraightTube',
          x: 2,
          y: 7,
          width: 1,
          height: 1,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {},
          flipped: false,
          type: 'StraightTube',
          x: 16,
          y: 9,
          width: 1,
          height: 1,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {
            [VALVE_CLOSED_KEY]: true,
          },
          flipped: false,
          type: 'Valve',
          x: 14,
          y: 9,
          width: 1,
          height: 1,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {},
          flipped: false,
          type: 'TeeTube',
          x: 18,
          y: 9,
          width: 1,
          height: 1,
        },
        {
          id: nanoid(),
          rotate: 180,
          settings: {
            [VALVE_CLOSED_KEY]: true,
          },
          flipped: false,
          type: 'Valve',
          x: 19,
          y: 9,
          width: 1,
          height: 1,
        },
        {
          id: nanoid(),
          rotate: 180,
          settings: {},
          flipped: false,
          type: 'SystemIO',
          x: 20,
          y: 9,
          width: 1,
          height: 1,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {},
          flipped: false,
          type: 'TeeTube',
          x: 7,
          y: 9,
          width: 1,
          height: 1,
        },
        {
          id: nanoid(),
          rotate: 270,
          settings: {
            [IO_ENABLED_KEY]: false,
          },
          flipped: false,
          type: 'Pump',
          x: 7,
          y: 8,
          width: 1,
          height: 1,
        },
        {
          id: nanoid(),
          rotate: 180,
          settings: {
            [VALVE_CLOSED_KEY]: true,
          },
          flipped: false,
          type: 'Valve',
          x: 8,
          y: 9,
          width: 1,
          height: 1,
        },
        {
          id: nanoid(),
          rotate: 180,
          settings: {
            [VALVE_CLOSED_KEY]: true,
          },
          flipped: false,
          type: 'Valve',
          x: 6,
          y: 9,
          width: 1,
          height: 1,
        },
        {
          id: nanoid(),
          rotate: 270,
          settings: {},
          flipped: false,
          type: 'ElbowTube',
          x: 8,
          y: 7,
          width: 1,
          height: 1,
        },
        {
          id: nanoid(),
          rotate: 90,
          settings: {},
          flipped: false,
          type: 'ElbowTube',
          x: 7,
          y: 7,
          width: 1,
          height: 1,
        },
        {
          id: nanoid(),
          rotate: 180,
          settings: {},
          flipped: false,
          type: 'ElbowTube',
          x: 11,
          y: 4,
          width: 1,
          height: 1,
        },
        {
          id: nanoid(),
          rotate: 90,
          settings: {},
          flipped: false,
          type: 'StraightTube',
          x: 11,
          y: 5,
          width: 1,
          height: 1,
        },
        {
          id: nanoid(),
          rotate: 180,
          settings: {},
          flipped: false,
          type: 'ElbowTube',
          x: 10,
          y: 5,
          width: 1,
          height: 1,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {},
          flipped: false,
          type: 'StraightTube',
          x: 10,
          y: 4,
          width: 1,
          height: 1,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {},
          flipped: false,
          type: 'BridgeTube',
          x: 9,
          y: 4,
          width: 1,
          height: 1,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {},
          flipped: false,
          type: 'BridgeTube',
          x: 9,
          y: 5,
          width: 1,
          height: 1,
        },
        {
          id: nanoid(),
          rotate: 180,
          settings: {},
          flipped: false,
          type: 'StraightTube',
          x: 8,
          y: 4,
          width: 1,
          height: 1,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {},
          flipped: false,
          type: 'StraightTube',
          x: 8,
          y: 5,
          width: 1,
          height: 1,
        },
        {
          id: nanoid(),
          rotate: 90,
          settings: {},
          flipped: false,
          type: 'StraightTube',
          x: 9,
          y: 3,
          width: 1,
          height: 1,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {
            [BORDER_KEY]: false,
            [PID_KEY]: typed<BlockAddress>({
              serviceId,
              id: names.mtPid,
              type: null,
            }),
          },
          flipped: false,
          type: 'PidDisplay',
          x: 11,
          y: 1,
          width: 1,
          height: 1,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {
            [BORDER_KEY]: false,
            [PID_KEY]: typed<BlockAddress>({
              serviceId,
              id: names.bkPid,
              type: null,
            }),
          },
          flipped: false,
          type: 'PidDisplay',
          x: 19,
          y: 1,
          width: 1,
          height: 1,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {
            [BORDER_KEY]: false,
            [PID_KEY]: typed<BlockAddress>({
              serviceId,
              id: names.hltPid,
              type: null,
            }),
          },
          flipped: false,
          type: 'PidDisplay',
          x: 3,
          y: 1,
          width: 1,
          height: 1,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {
            [BORDER_KEY]: false,
            [DRIVER_KEY]: typed<BlockAddress>({
              serviceId,
              id: names.hltDriver,
              type: null,
            }),
          },
          flipped: false,
          type: 'SetpointDriverDisplay',
          x: 8,
          y: 1,
          width: 2,
          height: 1,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {},
          flipped: false,
          type: 'TeeTube',
          x: 2,
          y: 9,
          width: 1,
          height: 1,
        },
        {
          id: nanoid(),
          rotate: 180,
          settings: {
            [VALVE_CLOSED_KEY]: true,
          },
          flipped: false,
          type: 'Valve',
          x: 1,
          y: 9,
          width: 1,
          height: 1,
        },
        {
          id: nanoid(),
          rotate: 270,
          settings: {
            [VALVE_CLOSED_KEY]: true,
          },
          flipped: false,
          type: 'Valve',
          x: 2,
          y: 8,
          width: 1,
          height: 1,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {
            [IO_ENABLED_KEY]: true,
            [IO_PRESSURE_KEY]: 10,
            [COLOR_KEY]: COLD_WATER,
          },
          flipped: false,
          type: 'SystemIO',
          x: 0,
          y: 9,
          width: 1,
          height: 1,
        },
      ],
    },
  ];
}
