import { nanoid } from 'nanoid';

import { BuilderLayout } from '@/plugins/builder/types';

import { withPrefix } from '../utils';
import { HermsConfig } from './types';

export function defineLayouts(config: HermsConfig): BuilderLayout[] {
  const { serviceId, names } = config;
  return [
    {
      id: nanoid(),
      title: withPrefix(config.prefix, 'Layout'),
      width: 26,
      height: 11,
      parts: [
        {
          id: nanoid(),
          rotate: 0,
          settings: { color: '#c48600' },
          flipped: false,
          type: 'Kettle',
          x: 20,
          y: 1,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: { color: '#9c4b00' },
          flipped: false,
          type: 'Kettle',
          x: 12,
          y: 1,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: { color: '#b50000' },
          flipped: false,
          type: 'Kettle',
          x: 4,
          y: 1,
        },
        {
          id: nanoid(),
          rotate: 180,
          settings: {},
          flipped: false,
          type: 'Coil',
          x: 5,
          y: 4,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {
            pwm: { serviceId, blockId: names.bkPwm },
            sizeX: 4,
          },
          flipped: true,
          type: 'HeatingElement',
          x: 21,
          y: 6,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {
            pwm: { serviceId, blockId: names.hltPwm },
            sizeX: 4,
          },
          flipped: false,
          type: 'HeatingElement',
          x: 3,
          y: 6,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {},
          flipped: false,
          type: 'WhirlpoolInlet',
          x: 20,
          y: 2,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {},
          flipped: false,
          type: 'WhirlpoolInlet',
          x: 4,
          y: 2,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: { sizeX: 4 },
          flipped: true,
          type: 'FilterBottom',
          x: 12,
          y: 6,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {
            bordered: false,
            setpoint: { serviceId, blockId: names.mtSetpoint },
          },
          flipped: false,
          type: 'SetpointDisplay',
          x: 13,
          y: 3,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {
            bordered: false,
            setpoint: { serviceId, blockId: names.bkSetpoint },
          },
          flipped: false,
          type: 'SetpointDisplay',
          x: 21,
          y: 3,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {
            bordered: false,
            setpoint: { serviceId, blockId: names.hltSetpoint },
          },
          flipped: false,
          type: 'SetpointDisplay',
          x: 5,
          y: 3,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {},
          flipped: false,
          type: 'StraightTube',
          x: 19,
          y: 2,
        },
        {
          id: nanoid(),
          rotate: 90,
          settings: {},
          flipped: false,
          type: 'ElbowTube',
          x: 18,
          y: 2,
        },
        {
          id: nanoid(),
          rotate: 90,
          settings: {},
          flipped: false,
          type: 'StraightTube',
          x: 18,
          y: 3,
        },
        {
          id: nanoid(),
          rotate: 90,
          settings: {},
          flipped: false,
          type: 'StraightTube',
          x: 18,
          y: 4,
        },
        {
          id: nanoid(),
          rotate: 90,
          settings: {},
          flipped: false,
          type: 'StraightTube',
          x: 18,
          y: 5,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {},
          flipped: false,
          type: 'BridgeTube',
          x: 18,
          y: 6,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {},
          flipped: false,
          type: 'StraightTube',
          x: 11,
          y: 2,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {},
          flipped: false,
          type: 'StraightTube',
          x: 10,
          y: 2,
        },
        {
          id: nanoid(),
          rotate: 90,
          settings: {},
          flipped: false,
          type: 'ElbowTube',
          x: 9,
          y: 2,
        },
        {
          id: nanoid(),
          rotate: 90,
          settings: {},
          flipped: false,
          type: 'StraightTube',
          x: 11,
          y: 6,
        },
        {
          id: nanoid(),
          rotate: 90,
          settings: {},
          flipped: false,
          type: 'StraightTube',
          x: 10,
          y: 6,
        },
        {
          id: nanoid(),
          rotate: 90,
          settings: {},
          flipped: false,
          type: 'StraightTube',
          x: 9,
          y: 6,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {},
          flipped: false,
          type: 'DipTube',
          x: 12,
          y: 2,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {},
          flipped: false,
          type: 'DipTube',
          x: 20,
          y: 6,
        },
        {
          id: nanoid(),
          rotate: 180,
          settings: {},
          flipped: false,
          type: 'TeeTube',
          x: 17,
          y: 6,
        },
        {
          id: nanoid(),
          rotate: 180,
          settings: { closed: true },
          flipped: false,
          type: 'Valve',
          x: 16,
          y: 6,
        },
        {
          id: nanoid(),
          rotate: 180,
          settings: { closed: true },
          flipped: false,
          type: 'Valve',
          x: 19,
          y: 6,
        },
        {
          id: nanoid(),
          rotate: 90,
          settings: {},
          flipped: false,
          type: 'ElbowTube',
          x: 2,
          y: 2,
        },
        {
          id: nanoid(),
          rotate: 90,
          settings: {},
          flipped: false,
          type: 'StraightTube',
          x: 2,
          y: 3,
        },
        {
          id: nanoid(),
          rotate: 90,
          settings: {},
          flipped: false,
          type: 'StraightTube',
          x: 2,
          y: 4,
        },
        {
          id: nanoid(),
          rotate: 90,
          settings: {},
          flipped: false,
          type: 'StraightTube',
          x: 2,
          y: 5,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {},
          flipped: true,
          type: 'DipTube',
          x: 7,
          y: 6,
        },
        {
          id: nanoid(),
          rotate: 180,
          settings: {},
          flipped: false,
          type: 'ElbowTube',
          x: 8,
          y: 6,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {},
          flipped: false,
          type: 'TeeTube',
          x: 17,
          y: 9,
        },
        {
          id: nanoid(),
          rotate: 270,
          settings: { closed: true },
          flipped: false,
          type: 'Valve',
          x: 18,
          y: 8,
        },
        {
          id: nanoid(),
          rotate: 90,
          settings: {},
          flipped: false,
          type: 'StraightTube',
          x: 18,
          y: 7,
        },
        {
          id: nanoid(),
          rotate: 90,
          settings: {},
          flipped: false,
          type: 'StraightTube',
          x: 17,
          y: 7,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {},
          flipped: false,
          type: 'StraightTube',
          x: 15,
          y: 9,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {},
          flipped: false,
          type: 'TeeTube',
          x: 9,
          y: 9,
        },
        {
          id: nanoid(),
          rotate: 270,
          settings: { enabled: false },
          flipped: false,
          type: 'Pump',
          x: 17,
          y: 8,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {},
          flipped: false,
          type: 'StraightTube',
          x: 3,
          y: 9,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {},
          flipped: false,
          type: 'StraightTube',
          x: 4,
          y: 9,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {},
          flipped: false,
          type: 'StraightTube',
          x: 5,
          y: 9,
        },
        {
          id: nanoid(),
          rotate: 90,
          settings: {},
          flipped: false,
          type: 'StraightTube',
          x: 2,
          y: 6,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {},
          flipped: false,
          type: 'StraightTube',
          x: 3,
          y: 2,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {},
          flipped: false,
          type: 'TeeTube',
          x: 13,
          y: 9,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {},
          flipped: false,
          type: 'TeeTube',
          x: 11,
          y: 9,
        },
        {
          id: nanoid(),
          rotate: 90,
          settings: { closed: true },
          flipped: false,
          type: 'Valve',
          x: 13,
          y: 8,
        },
        {
          id: nanoid(),
          rotate: 90,
          settings: { closed: true },
          flipped: false,
          type: 'Valve',
          x: 11,
          y: 8,
        },
        {
          id: nanoid(),
          rotate: 90,
          settings: { closed: true },
          flipped: false,
          type: 'Valve',
          x: 9,
          y: 8,
        },
        {
          id: nanoid(),
          rotate: 90,
          settings: {},
          flipped: false,
          type: 'StraightTube',
          x: 9,
          y: 7,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {},
          flipped: false,
          type: 'StraightTube',
          x: 12,
          y: 7,
        },
        {
          id: nanoid(),
          rotate: 180,
          settings: { closed: true },
          flipped: false,
          type: 'Valve',
          x: 10,
          y: 9,
        },
        {
          id: nanoid(),
          rotate: 180,
          settings: { closed: true },
          flipped: false,
          type: 'Valve',
          x: 12,
          y: 9,
        },
        {
          id: nanoid(),
          rotate: 180,
          settings: {},
          flipped: false,
          type: 'ElbowTube',
          x: 13,
          y: 7,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {},
          flipped: false,
          type: 'BridgeTube',
          x: 11,
          y: 7,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {},
          flipped: false,
          type: 'ElbowTube',
          x: 10,
          y: 7,
        },
        {
          id: nanoid(),
          rotate: 90,
          settings: {},
          flipped: false,
          type: 'StraightTube',
          x: 2,
          y: 7,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {},
          flipped: false,
          type: 'StraightTube',
          x: 16,
          y: 9,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: { closed: true },
          flipped: false,
          type: 'Valve',
          x: 14,
          y: 9,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {},
          flipped: false,
          type: 'TeeTube',
          x: 18,
          y: 9,
        },
        {
          id: nanoid(),
          rotate: 180,
          settings: { closed: true },
          flipped: false,
          type: 'Valve',
          x: 19,
          y: 9,
        },
        {
          id: nanoid(),
          rotate: 180,
          settings: {},
          flipped: false,
          type: 'SystemIO',
          x: 20,
          y: 9,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {},
          flipped: false,
          type: 'TeeTube',
          x: 7,
          y: 9,
        },
        {
          id: nanoid(),
          rotate: 270,
          settings: { enabled: false },
          flipped: false,
          type: 'Pump',
          x: 7,
          y: 8,
        },
        {
          id: nanoid(),
          rotate: 180,
          settings: { closed: true },
          flipped: false,
          type: 'Valve',
          x: 8,
          y: 9,
        },
        {
          id: nanoid(),
          rotate: 180,
          settings: { closed: true },
          flipped: false,
          type: 'Valve',
          x: 6,
          y: 9,
        },
        {
          id: nanoid(),
          rotate: 270,
          settings: {},
          flipped: false,
          type: 'ElbowTube',
          x: 8,
          y: 7,
        },
        {
          id: nanoid(),
          rotate: 90,
          settings: {},
          flipped: false,
          type: 'ElbowTube',
          x: 7,
          y: 7,
        },
        {
          id: nanoid(),
          rotate: 180,
          settings: {},
          flipped: false,
          type: 'ElbowTube',
          x: 11,
          y: 4,
        },
        {
          id: nanoid(),
          rotate: 90,
          settings: {},
          flipped: false,
          type: 'StraightTube',
          x: 11,
          y: 5,
        },
        {
          id: nanoid(),
          rotate: 180,
          settings: {},
          flipped: false,
          type: 'ElbowTube',
          x: 10,
          y: 5,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {},
          flipped: false,
          type: 'StraightTube',
          x: 10,
          y: 4,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {},
          flipped: false,
          type: 'BridgeTube',
          x: 9,
          y: 4,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {},
          flipped: false,
          type: 'BridgeTube',
          x: 9,
          y: 5,
        },
        {
          id: nanoid(),
          rotate: 180,
          settings: {},
          flipped: false,
          type: 'StraightTube',
          x: 8,
          y: 4,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {},
          flipped: false,
          type: 'StraightTube',
          x: 8,
          y: 5,
        },
        {
          id: nanoid(),
          rotate: 90,
          settings: {},
          flipped: false,
          type: 'StraightTube',
          x: 9,
          y: 3,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {
            bordered: false,
            pid: {
              serviceId,
              blockId: names.mtPid,
            },
          },
          flipped: false,
          type: 'PidDisplay',
          x: 11,
          y: 1,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {
            bordered: false,
            pid: {
              serviceId,
              blockId: names.bkPid,
            },
          },
          flipped: false,
          type: 'PidDisplay',
          x: 19,
          y: 1,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {
            bordered: false,
            pid: {
              serviceId,
              blockId: names.hltPid,
            },
          },
          flipped: false,
          type: 'PidDisplay',
          x: 3,
          y: 1,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {
            bordered: false,
            setpointDriver: {
              serviceId,
              blockId: names.hltDriver,
            },
          },
          flipped: false,
          type: 'SetpointDriverDisplay',
          x: 8,
          y: 1,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {},
          flipped: false,
          type: 'TeeTube',
          x: 2,
          y: 9,
        },
        {
          id: nanoid(),
          rotate: 180,
          settings: { closed: true },
          flipped: false,
          type: 'Valve',
          x: 1,
          y: 9,
        },
        {
          id: nanoid(),
          rotate: 270,
          settings: { closed: true },
          flipped: false,
          type: 'Valve',
          x: 2,
          y: 8,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: { pressure: 10, liqnanoids: ['#4AA0EF'] },
          flipped: false,
          type: 'SystemIO',
          x: 0,
          y: 9,
        },
      ],
    },
  ];
}
