import Vue from 'vue';
import Quasar, {
  QLayout,
  QLayoutHeader,
  QLayoutDrawer,
  QPageContainer,
  QPage,
  QToolbar,
  QToolbarTitle,
  QBtn,
  QAlert,
  QBtnGroup,
  QIcon,
  QList,
  QListHeader,
  QItem,
  QItemMain,
  QItemSide,
  QItemTile,
  QItemSeparator,
  QModal,
  QModalLayout,
  QInnerLoading,
  QSpinner,
  QCard,
  QCardActions,
  QCardTitle,
  QCardSeparator,
  QCardMain,
  QInput,
  QSelect,
  QStepper,
  QStep,
  QStepperNavigation,
  QRadio,
  QField,
  QOptionGroup,
  Ripple,
  Notify,
  Dialog,
  CloseOverlay,
  QToggle,
} from 'quasar';

import 'quasar-extras/roboto-font';
import 'quasar-extras/material-icons';
import 'quasar-extras/mdi';
import 'quasar-extras/animate/bounceInLeft.css';
import 'quasar-extras/animate/bounceOutRight.css';

import './css/app.styl';

Vue.use(Quasar, {
  components: {
    QLayout,
    QLayoutHeader,
    QLayoutDrawer,
    QPageContainer,
    QPage,
    QToolbar,
    QToolbarTitle,
    QAlert,
    QBtn,
    QBtnGroup,
    QIcon,
    QList,
    QListHeader,
    QItem,
    QItemMain,
    QItemSide,
    QItemTile,
    QItemSeparator,
    QModal,
    QModalLayout,
    QInnerLoading,
    QSpinner,
    QCard,
    QCardActions,
    QCardTitle,
    QCardSeparator,
    QCardMain,
    QInput,
    QSelect,
    QStepper,
    QStep,
    QStepperNavigation,
    QRadio,
    QField,
    QOptionGroup,
    QToggle,
  },
  directives: { Ripple, CloseOverlay },
  plugins: { Notify, Dialog },
});
