import Quasar, {
  CloseOverlay,
  Dialog,
  Notify,
  QAlert,
  QBtn,
  QBtnGroup,
  QCard,
  QCardActions,
  QCardMain,
  QCardSeparator,
  QCardTitle,
  QCarousel,
  QCarouselControl,
  QCarouselSlide,
  QCollapsible,
  QDatetime,
  QDatetimePicker,
  QField,
  QIcon,
  QInnerLoading,
  QInput,
  QItem,
  QItemMain,
  QItemSeparator,
  QItemSide,
  QItemTile,
  QLayout,
  QLayoutDrawer,
  QLayoutHeader,
  QList,
  QListHeader,
  QModal,
  QModalLayout,
  QOptionGroup,
  QPage,
  QPageContainer,
  QPopover,
  QPopupEdit,
  QRadio,
  QScrollArea,
  QSearch,
  QSelect,
  QSpinner,
  QStep,
  QStepper,
  QStepperNavigation,
  QToggle,
  QToolbar,
  QToolbarTitle,
  Ripple,
} from 'quasar';
import Vue from 'vue';

import 'quasar-extras/animate/bounceInLeft.css';
import 'quasar-extras/animate/bounceOutRight.css';
import 'quasar-extras/material-icons';
import 'quasar-extras/mdi';
import 'quasar-extras/roboto-font';

import './css/app.styl';

Vue.use(Quasar, {
  components: {
    QAlert,
    QBtn,
    QBtnGroup,
    QCard,
    QCardActions,
    QCardMain,
    QCardSeparator,
    QCardTitle,
    QCarousel,
    QCarouselControl,
    QCarouselSlide,
    QCollapsible,
    QDatetime,
    QDatetimePicker,
    QField,
    QIcon,
    QInnerLoading,
    QInput,
    QItem,
    QItemMain,
    QItemSeparator,
    QItemSide,
    QItemTile,
    QLayout,
    QLayoutDrawer,
    QLayoutHeader,
    QList,
    QListHeader,
    QModal,
    QModalLayout,
    QOptionGroup,
    QPage,
    QPageContainer,
    QPopover,
    QPopupEdit,
    QRadio,
    QScrollArea,
    QSearch,
    QSelect,
    QSpinner,
    QStep,
    QStepper,
    QStepperNavigation,
    QToggle,
    QToolbar,
    QToolbarTitle,
  },
  directives: { Ripple, CloseOverlay },
  plugins: { Notify, Dialog },
});
