import { BuilderLayout } from '@/plugins/builder/types';
import { nanoid } from 'nanoid';
import { withPrefix } from '../utils';
import { RimsConfig } from './types';

export function defineLayouts(config: RimsConfig): BuilderLayout[] {
  const { serviceId, names } = config;
  return [
    {
      id: nanoid(),
      title: withPrefix(config.prefix, 'Layout'),
      width: 12,
      height: 12,
      parts: [
        {
          id: nanoid(),
          rotate: 0,
          settings: {
            color: '#E1AC00',
          },
          flipped: false,
          type: 'Kettle',
          x: 4,
          y: 1,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {},
          flipped: false,
          type: 'FilterBottom',
          x: 4,
          y: 6,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {
            sizeX: 4,
            pwm: { serviceId, blockId: names.tubePwm },
          },
          flipped: false,
          type: 'RimsTube',
          x: 3,
          y: 9,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {},
          flipped: true,
          type: 'WhirlpoolInlet',
          x: 7,
          y: 1,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {
            bordered: false,
            setpoint: { serviceId, blockId: names.kettleSetpoint },
          },
          flipped: false,
          type: 'SetpointDisplay',
          x: 5,
          y: 2,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {
            setpoint: { serviceId, blockId: names.tubeSetpoint },
          },
          flipped: false,
          type: 'SetpointDisplay',
          x: 7,
          y: 8,
        },
        {
          id: nanoid(),
          rotate: 90,
          settings: {},
          flipped: false,
          type: 'StraightTube',
          x: 9,
          y: 6,
        },
        {
          id: nanoid(),
          rotate: 90,
          settings: {},
          flipped: false,
          type: 'StraightTube',
          x: 9,
          y: 5,
        },
        {
          id: nanoid(),
          rotate: 180,
          settings: {},
          flipped: false,
          type: 'StraightTube',
          x: 8,
          y: 1,
        },
        {
          id: nanoid(),
          rotate: 180,
          settings: {},
          flipped: false,
          type: 'ElbowTube',
          x: 9,
          y: 1,
        },
        {
          id: nanoid(),
          rotate: 90,
          settings: {},
          flipped: false,
          type: 'StraightTube',
          x: 9,
          y: 4,
        },
        {
          id: nanoid(),
          rotate: 90,
          settings: {},
          flipped: false,
          type: 'StraightTube',
          x: 9,
          y: 3,
        },
        {
          id: nanoid(),
          rotate: 90,
          settings: {},
          flipped: false,
          type: 'StraightTube',
          x: 9,
          y: 2,
        },
        {
          id: nanoid(),
          rotate: 90,
          settings: {},
          flipped: false,
          type: 'ElbowTube',
          x: 2,
          y: 6,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {},
          flipped: false,
          type: 'Valve',
          x: 3,
          y: 6,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {},
          flipped: false,
          type: 'ElbowTube',
          x: 2,
          y: 8,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {
            enabled: true,
            actuator: { serviceId, blockId: names.pumpAct },
          },
          flipped: true,
          type: 'Pump',
          x: 3,
          y: 8,
        },
        {
          id: nanoid(),
          rotate: 180,
          settings: {},
          flipped: false,
          type: 'ElbowTube',
          x: 4,
          y: 8,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {
            bordered: false,
            pid: { serviceId, blockId: names.tubePid },
          },
          flipped: false,
          type: 'PidDisplay',
          x: 2,
          y: 9,
        },
        {
          id: nanoid(),
          rotate: 90,
          settings: {},
          flipped: false,
          type: 'StraightTube',
          x: 9,
          y: 7,
        },
        {
          id: nanoid(),
          rotate: 90,
          settings: {},
          flipped: false,
          type: 'StraightTube',
          x: 2,
          y: 7,
        },
        {
          id: nanoid(),
          rotate: 90,
          settings: {},
          flipped: false,
          type: 'ElbowTube',
          x: 6,
          y: 8,
        },
        {
          id: nanoid(),
          rotate: 270,
          settings: {},
          flipped: false,
          type: 'ElbowTube',
          x: 9,
          y: 8,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {
            bordered: false,
            pid: { serviceId, blockId: names.kettlePid },
          },
          flipped: false,
          type: 'PidDisplay',
          x: 1,
          y: 9,
        },
      ],
    },
  ];
}
