import {
  BORDER_KEY,
  COLOR_KEY,
  PID_KEY,
  PUMP_KEY,
  PWM_KEY,
  SETPOINT_KEY,
  WIDTH_KEY,
} from '@/plugins/builder/const';
import { BuilderLayout } from '@/plugins/builder/types';
import { BlockAddress } from '@/plugins/spark/types';
import { typed } from '@/utils/misc';
import { nanoid } from 'nanoid';
import { withPrefix } from '../utils';
import { RimsConfig } from './types';

export function defineLayouts(config: RimsConfig): BuilderLayout[] {
  const { serviceId, names } = config;
  return [
    {
      id: nanoid(),
      title: withPrefix(config.prefix, 'Layout'),
      width: 12,
      height: 12,
      parts: [
        {
          id: nanoid(),
          rotate: 0,
          settings: {
            [COLOR_KEY]: '#E1AC00',
          },
          flipped: false,
          type: 'Kettle',
          x: 4,
          y: 1,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {},
          flipped: false,
          type: 'FilterBottom',
          x: 4,
          y: 6,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {
            [WIDTH_KEY]: 4,
            [PWM_KEY]: typed<BlockAddress>({
              serviceId,
              id: names.tubePwm,
              type: null,
            }),
          },
          flipped: false,
          type: 'RimsTube',
          x: 3,
          y: 9,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {},
          flipped: true,
          type: 'WhirlpoolInlet',
          x: 7,
          y: 1,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {
            [BORDER_KEY]: false,
            [SETPOINT_KEY]: typed<BlockAddress>({
              serviceId,
              id: names.kettleSetpoint,
              type: null,
            }),
          },
          flipped: false,
          type: 'SetpointDisplay',
          x: 5,
          y: 2,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {
            [SETPOINT_KEY]: typed<BlockAddress>({
              serviceId,
              id: names.tubeSetpoint,
              type: null,
            }),
          },
          flipped: false,
          type: 'SetpointDisplay',
          x: 7,
          y: 8,
        },
        {
          id: nanoid(),
          rotate: 90,
          settings: {},
          flipped: false,
          type: 'StraightTube',
          x: 9,
          y: 6,
        },
        {
          id: nanoid(),
          rotate: 90,
          settings: {},
          flipped: false,
          type: 'StraightTube',
          x: 9,
          y: 5,
        },
        {
          id: nanoid(),
          rotate: 180,
          settings: {},
          flipped: false,
          type: 'StraightTube',
          x: 8,
          y: 1,
        },
        {
          id: nanoid(),
          rotate: 180,
          settings: {},
          flipped: false,
          type: 'ElbowTube',
          x: 9,
          y: 1,
        },
        {
          id: nanoid(),
          rotate: 90,
          settings: {},
          flipped: false,
          type: 'StraightTube',
          x: 9,
          y: 4,
        },
        {
          id: nanoid(),
          rotate: 90,
          settings: {},
          flipped: false,
          type: 'StraightTube',
          x: 9,
          y: 3,
        },
        {
          id: nanoid(),
          rotate: 90,
          settings: {},
          flipped: false,
          type: 'StraightTube',
          x: 9,
          y: 2,
        },
        {
          id: nanoid(),
          rotate: 90,
          settings: {},
          flipped: false,
          type: 'ElbowTube',
          x: 2,
          y: 6,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {},
          flipped: false,
          type: 'Valve',
          x: 3,
          y: 6,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {},
          flipped: false,
          type: 'ElbowTube',
          x: 2,
          y: 8,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {
            [PUMP_KEY]: typed<BlockAddress>({
              serviceId,
              id: names.pumpAct,
              type: null,
            }),
          },
          flipped: true,
          type: 'Pump',
          x: 3,
          y: 8,
        },
        {
          id: nanoid(),
          rotate: 180,
          settings: {},
          flipped: false,
          type: 'ElbowTube',
          x: 4,
          y: 8,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {
            [BORDER_KEY]: false,
            [PID_KEY]: typed<BlockAddress>({
              serviceId,
              id: names.tubePid,
              type: null,
            }),
          },
          flipped: false,
          type: 'PidDisplay',
          x: 2,
          y: 9,
        },
        {
          id: nanoid(),
          rotate: 90,
          settings: {},
          flipped: false,
          type: 'StraightTube',
          x: 9,
          y: 7,
        },
        {
          id: nanoid(),
          rotate: 90,
          settings: {},
          flipped: false,
          type: 'StraightTube',
          x: 2,
          y: 7,
        },
        {
          id: nanoid(),
          rotate: 90,
          settings: {},
          flipped: false,
          type: 'ElbowTube',
          x: 6,
          y: 8,
        },
        {
          id: nanoid(),
          rotate: 270,
          settings: {},
          flipped: false,
          type: 'ElbowTube',
          x: 9,
          y: 8,
        },
        {
          id: nanoid(),
          rotate: 0,
          settings: {
            [BORDER_KEY]: false,
            [PID_KEY]: typed<BlockAddress>({
              serviceId,
              id: names.kettlePid,
              type: null,
            }),
          },
          flipped: false,
          type: 'PidDisplay',
          x: 1,
          y: 9,
        },
      ],
    },
  ];
}
