name: CI build

on:
  push:
    branches: ['**']
  pull_request:
    branches: [develop, edge]

jobs:
  build:
    if: github.repository_owner == 'BrewBlox'
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Get image metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/brewblox/brewblox-ui

      - name: ghcr.io login
        uses: docker/login-action@v2
        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: yarn ci
      - run: yarn build
        env:
          NODE_OPTIONS: --max_old_space_size=16384
      - run: yarn lint
      - run: yarn test:ci
      - run: cp -rf dist/ docker/

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8
          context: docker
